<a href="https://colab.research.google.com/github/solanods/pandas/blob/master/alteracoes_rmops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Imports
from re import search

import pandas as pd
pd.set_option('display.max_rows', 5000)
pd.set_option('display.max_columns', 5000)

from google.colab import drive
drive.mount('/content/drive')

from datetime import date

Mounted at /content/drive

In [ ]:
# Carregamento dos dados
df_original = pd.read_excel('/content/PRMS_09_SET_2022ontem.xlsm', sheet_name='RMOP')
df_alterado = pd.read_excel('/content/PRMS_09_SET_2022.xlsm', sheet_name='RMOP')

/usr/local/lib/python3.7/dist-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [ ]:
# Funcao limpeza de dados

def tratarDataframe(df):
  
  # Selecionar colunas de interesse
  df = df.iloc[:,[3,5,6,7,8,11,16,17,18,19]]

  # Renomear colunas
  df = df.rename({'Unnamed: 3': 'DIA',
                  'Unnamed: 5': 'PREVISTO',
                  'Unnamed: 6': 'ESCALA',
                  'Unnamed: 7': 'TOTVS',
                  'Unnamed: 8': 'JORNADA',
                  'Unnamed: 11': 'ENTRADA',
                  'Unnamed: 16': 'CODIGO',
                  'Unnamed: 17': 'DESCRICAO',
                  'Unnamed: 18': 'OBSERVACOES',
                  'Unnamed: 19': 'RE_SGT'}, axis = 1)

  # Remover nan
  df = df.fillna('-')

  # Obter lista com nome de todos operadores
  operadores = []
  for linha in df.index:
    if search ('[A-Z]+', str(df['DIA'][linha])):
      operadores.append(df['DIA'][linha])

  operadores = [operador for operador in operadores if operador.isupper()]

  # Extrair rmop
  i = 3
  j =38
  R = []
  df['NOME'] = ''
  df['RE'] = ''
  for operador in operadores:
    df['NOME'].loc[i:j] = operador
    rmop_operador = df.loc[i:j]
    R.append(rmop_operador)
    df['RE'].loc[i:j] = df['ENTRADA'].loc[i:j].iloc[0]
    i+=66
    j+=66

  return df

In [ ]:
df_original = tratarDataframe(df_original)
df_alterado = tratarDataframe(df_alterado)

In [ ]:
# Criar novo df somente com os índices modificados, ou seja, as diferenças entre ambos
rmops_alterado = pd.concat([df_original,df_alterado]).drop_duplicates(keep=False)

In [ ]:
# Resultado mostra os indices originais e alterados em sequencia
rmops_alterado

,DIA,PREVISTO,ESCALA,TOTVS,JORNADA,ENTRADA,CODIGO,DESCRICAO,OBSERVACOES,RE_SGT,NOME,RE
1283,22,TRAB,MA,3-C,NPT,21:30:00,C083,Troca Missão,C/ Trintinaia,2445,BARCELLOS,542
2076,23,TRAB,G3,17-Q,07M,05:10:00,-,-,-,-,CIBELE,3193
2081,28,FOL,G3,17-Q,FOL,,-,-,-,-,CIBELE,3193
2472,23,FOL,J1,13-M,FOL,,D,Disponível para HE,-,-,COITINHO,3609
2476,27,TRAB,J1,13-M,11T,12:00:00,-,-,-,542/2906,COITINHO,3609
3005,28,TRAB,EAA,2-B,EMP1,TRAR EX,EMP,Lançar em jornada,-,257,DIEGO,2394
3255,14,FOL,J2,13-M,09T,13:30:00,HEFT,HE folga TARDE,FALTA TORRES,252,EDNA,3094
3459,20,TRAB,O1,3-C,12T,14:40:00,-,-,-,-,ENEDIR,525
3593,22,FOL,M2,7-G,FOL,,-,-,-,-,FAGUNDES,1576
3594,23,TRAB,M2,7-G,19T,13:30:00,-,-,-,-,FAGUNDES,1576
4254,23,TRAB,L3,9-I,08T,12:20:00,-,-,-,-,FULBER,1252
5046,23,TRAB,Q1,17-Q,11T,12:00:00,-,-,-,-,INES,2424
5047,24,TRAB,Q1,17-Q,12T,13:35:00,-,-,-,-,INES,2424
5048,25,TRAB,Q1,17-Q,08N,22:00:00,-,-,-,-,INES,2424
5049,26,TRAB,Q1,17-Q,03N,21:25:00,-,-,-,-,INES,2424
5050,27,FOL,Q1,17-Q,FOL,,-,-,-,-,INES,2424
5051,28,FOL,Q1,17-Q,FOL,,-,-,-,-,INES,2424
6958,21,TRAB,L2,9-I,10T,12:00:00,-,-,-,-,MACEDO,850
7026,23,TRAB,Y10,_,23T,13:10:00,-,-,-,-,MADALENA,972
7618,21,TRAB,K5,11-K,19T,13:30:00,-,-,-,-,MARTA,1425
7619,22,TRAB,K5,11-K,20T,12:30:00,-,-,-,-,MARTA,1425
7751,22,TRAB,OA,9-I,TNH,13:15:00,-,-,-,-,MAURICIO,2945
7949,22,TRAB,K6,11-K,30T,13:30:00,-,-,-,-,MIRANDA,577
7950,23,TRAB,K6,11-K,17N,21:30:00,-,-,-,-,MIRANDA,577
8213,22,TRAB,-,1-A,TPT,13:15:00,-,-,-,-,NOGUEIRA,1643
8475,20,TRAB,P6,1-A,21T,13:00:00,-,-,-,-,PACHECO,880
8476,21,TRAB,P6,1-A,31T,13:30:00,-,-,-,-,PACHECO,880
8477,22,TRAB,P6,1-A,31T,13:30:00,-,-,-,-,PACHECO,880
9797,22,TRAB,K4,11-K,19T,13:30:00,-,-,-,-,SAUL,585
11183,22,TRAB,P4,1-A,05T,13:15:00,-,-,-,-,VALLERIUS,1388
11512,21,TRAB,Y13,_,37T,13:30:00,-,-,Reciclagem pátio - TRE 14h,2923,VIEIRA,3317
11711,22,FOL,D4,5-E,FOL,,-,-,-,-,WIRTI,2398
1283,22,TRAB,MA,3-C,NE1,21:30:00,C083,Troca Missão,C/ Trintinaia,2445/2426,BARCELLOS,542
2076,23,TRAB,G3,17-Q,FOL,,C129,Troca Jorn,Por 28 sol func,2426,CIBELE,3193
2081,28,FOL,G3,17-Q,18M,05:20:00,C129,Troca Jorn,por 23 sol func,2426,CIBELE,3193
2472,23,FOL,J1,13-M,08T,12:20:00,C129,Troca Jorn,POR 27 nec operacional,-,COITINHO,3609
2476,27,TRAB,J1,13-M,FOL,,C129,Troca Jorn,por 23 nec operacional,542/2906/2426,COITINHO,3609
3005,28,TRAB,EAA,2-B,AMR1,05:10:00,-,-,-,-,DIEGO,2394
3255,14,FOL,J2,13-M,09T,13:30:00,HEFT,HE folga TARDE,FALTA TORRES . Sem intervalo nec operac. Assu...,252/2426,EDNA,3094
3459,20,TRAB,O1,3-C,12T,14:40:00,C123,Rel Inoper,-,2426,ENEDIR,525
3593,22,FOL,M2,7-G,FOL,,D,Disponível para HE,-,2426,FAGUNDES,1576
3594,23,TRAB,M2,7-G,05T,13:15:00,C083,Troca Missão,FURO,2426,FAGUNDES,1576
4254,23,TRAB,L3,9-I,12T,14:20:00,C083,Troca Missão,sol func,2426,FULBER,1252
5046,23,TRAB,Q1,17-Q,23T,13:10:00,C083,Troca Missão,COM MADALENA,2426,INES,2424
5047,24,TRAB,Q1,17-Q,FOL,,C129,Troca Jorn,por 27 sol func,2426,INES,2424
5048,25,TRAB,Q1,17-Q,FOL,,C129,Troca Jorn,por 28 sol func,2426,INES,2424
5049,26,TRAB,Q1,17-Q,02T,14:00:00,C500,Permuta,sol func,2426,INES,2424
5050,27,FOL,Q1,17-Q,26T,13:00:00,C129,Troca Jorn,por 24 sol func,2426,INES,2424
5051,28,FOL,Q1,17-Q,29T,13:30:00,C129,Troca Jorn,por 25 sol func,2426,INES,2424
6958,21,TRAB,L2,9-I,10T,12:00:00,C300,HE extensão jor,nec oper recolhimento atrasou,2426,MACEDO,850
7026,23,TRAB,Y10,_,11T,12:00:00,C083,Troca Missão,COM INES,2426,MADALENA,972
7618,21,TRAB,K5,11-K,25T,14:30:00,C083,Troca Missão,nec oper falta Vanderlei,2426,MARTA,1425
7619,22,TRAB,K5,11-K,28T,12:00:00,C083,Troca Missão,COM VALLERIUS,2426,MARTA,1425
7751,22,TRAB,OA,9-I,TPT,13:15:00,C083,Troca Missão,Ajuste de efetivo,2426,MAURICIO,2945
7949,22,TRAB,K6,11-K,08T,12:20:00,C083,Troca Missão,Ajuste de efetivo,2426,MIRANDA,577
7950,23,TRAB,K6,11-K,15T,13:30:00,C500,Permuta,nec oper,2426,MIRANDA,577
8213,22,TRAB,-,1-A,NPT,21:30:00,C500,Permuta,Ajuste de efetivo,2426,NOGUEIRA,1643
8475,20,TRAB,P6,1-A,FAT,COLOCAR,C208,Atestado,-,2426,PACHECO,880
8476,21,TRAB,P6,1-A,FAT,COLOCAR,C208,Atestado,-,2426,PACHECO,880
8477,22,TRAB,P6,1-A,FAT,COLOCAR,C208,Atestado,-,2426,PACHECO,880
9797,22,TRAB,K4,11-K,05T,13:15:00,C083,Troca Missão,C/ VALLERIUS,2426,SAUL,585
11183,22,TRAB,P4,1-A,20T,12:30:00,C083,Troca Missão,C/ SAUL +C083 MARTA Ajuste de efetivo,2426,VALLERIUS,1388
11512,21,TRAB,Y13,_,FAT,COLOCAR,LDV,Lançar em jornada,TREINAMENTO MESARIO TRE,2923/2426,VIEIRA,3317
11711,22,FOL,D4,5-E,03T,13:10:00,HEFT,HE folga TARDE,nec oper,2426,WIRTI,2398

In [ ]:
# Criar campo data
data_atual = date.today()
rmops_alterado['ALTERADO_EM'] = data_atual

In [ ]:
# Salvar no google drive
rmops_alterado.to_excel(f'/content/drive/MyDrive/alteracoesrmop{data_atual}.xlsx')

In [ ]:
# Numero de alteracoes
num_alteracoes = len(rmops_alterado.index)/2

In [ ]:
# String para arquivar
dados = str(data_atual) + '   N°_RMOPS_ALTERADOS: ' + str(int(num_alteracoes))

In [ ]:
dados

'2022-09-22   N°_RMOPS_ALTERADOS: 32'

In [ ]:
# Salvar em arquivo texto
file = open('/content/drive/MyDrive/alteracoes_rmop_contador.txt', 'a')
file.write(dados + '\n')
file.close()